import os
import json
from datetime import datetime
from database import init_db, get_db_connection, save_media_asset_to_db, get_uploads_dir, BASE_DIR

IMAGES_DIR = os.path.join(BASE_DIR, "static", "images", "phones")


def generate_phone_svg(slug: str, brand_name: str, model_name: str, accent_hex: str, secondary_hex: str, is_demo: bool = True) -> str:
    from phone_image_engine import render_exact_phone_svg
    return render_exact_phone_svg(slug, brand_name, model_name)


BRANDS_SEED = [
    {
        "name": "Apple",
        "slug": "apple",
        "country": "United States",
        "tagline": "iOS Flagships & Bionic Series",
        "description": "Explore Apple iPhone models in Pakistan with PKR pricing placeholders, PTA status options, and full hardware specification sheets.",
        "accent_color": "#3b82f6",
        "display_order": 1,
    },
    {
        "name": "Samsung",
        "slug": "samsung",
        "country": "South Korea",
        "tagline": "Galaxy S, Z Fold/Flip & Galaxy A Series",
        "description": "Browse Samsung Galaxy smartphones across flagship Ultra devices, foldable phones, and mid-range Galaxy A series models in Pakistan.",
        "accent_color": "#2563eb",
        "display_order": 2,
    },
    {
        "name": "Xiaomi",
        "slug": "xiaomi",
        "country": "China",
        "tagline": "Xiaomi Flagships, Redmi Note & POCO Lineup",
        "description": "Compare Xiaomi and Redmi smartphones with high-wattage HyperCharge, AMOLED displays, and competitive PKR price brackets.",
        "accent_color": "#f97316",
        "display_order": 3,
    },
    {
        "name": "Vivo",
        "slug": "vivo",
        "country": "China",
        "tagline": "ZEISS Optics X-Series & V-Series Portrait Phones",
        "description": "Discover Vivo smartphones featuring Aura Light portrait cameras, curved AMOLED screens, and slim battery architectures.",
        "accent_color": "#0ea5e9",
        "display_order": 4,
    },
    {
        "name": "Oppo",
        "slug": "oppo",
        "country": "China",
        "tagline": "Reno Portrait Series, Find Flagships & A-Series",
        "description": "View Oppo mobile phone specifications, SuperVOOC fast-charging details, and Pakistani Rupee (PKR) price listings.",
        "accent_color": "#10b981",
        "display_order": 5,
    },
    {
        "name": "OnePlus",
        "slug": "oneplus",
        "country": "China",
        "tagline": "Never Settle Flagship Killers & Nord Series",
        "description": "Explore OnePlus flagship and Nord smartphones featuring OxygenOS, Trinity Engine performance, and high-refresh Fluid AMOLED panels.",
        "accent_color": "#ef4444",
        "display_order": 6,
    },
    {
        "name": "Realme",
        "slug": "realme",
        "country": "China",
        "tagline": "GT Performance Series, Number Pro+ & C-Series",
        "description": "Compare Realme phones in Pakistan from budget C-series daily drivers to GT flagship gaming and periscope camera models.",
        "accent_color": "#eab308",
        "display_order": 7,
    },
    {
        "name": "Infinix",
        "slug": "infinix",
        "country": "Hong Kong",
        "tagline": "Note Series, GT Gaming, Zero & Hot Lineup",
        "description": "Browse Infinix smartphones known in Pakistan for All-Round FastCharge, high-refresh AMOLED displays, and gaming chipsets.",
        "accent_color": "#8b5cf6",
        "display_order": 8,
    },
    {
        "name": "Tecno",
        "slug": "tecno",
        "country": "Hong Kong",
        "tagline": "Camon Camera Series, Spark, Pova & Phantom Fold",
        "description": "Check Tecno Mobile specifications, Camon portrait imaging systems, Pova mega-battery gaming phones, and PKR pricing.",
        "accent_color": "#06b6d4",
        "display_order": 9,
    },
]


PHONES_SEED = [
    # APPLE
    {
        "brand_slug": "apple",
        "model_name": "iPhone 16 Pro Max",
        "slug": "apple-iphone-16-pro-max",
        "price_pkr": 524999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-09-20",
        "ram_gb": 8,
        "ram_display": "8 GB LPDDR5X",
        "storage_gb": 256,
        "storage_display": "256GB / 512GB / 1TB NVMe",
        "processor": "Apple A18 Pro (3 nm) — Hexa-core (2x4.05 GHz + 4x2.42 GHz), Apple 6-core GPU",
        "display_type": "LTPO Super Retina XDR OLED, 120Hz ProMotion, HDR10, Dolby Vision",
        "display_size_inch": 6.9,
        "display_resolution": "1320 x 2868 pixels (~460 ppi)",
        "refresh_rate": "120Hz Adaptive",
        "main_camera": "48 MP (wide, OIS) + 12 MP (periscope 5x optical zoom) + 48 MP (ultrawide) + TOF 3D LiDAR",
        "selfie_camera": "12 MP (wide, f/1.9, OIS, SL 3D Face ID sensor), 4K@60fps",
        "battery_mah": 4685,
        "charging": "30W wired PD2.0, 25W MagSafe wireless, 15W Qi2 wireless",
        "network": "GSM / CDMA / HSPA / EVDO / LTE / 5G SA/NSA",
        "is_5g": 1,
        "os": "iOS 18",
        "dimensions": "163 x 77.6 x 8.3 mm",
        "weight": "227 g",
        "build_material": "Grade 5 Titanium frame, Ceramic Shield front, textured matte glass back",
        "colors": "Desert Titanium, Natural Titanium, White Titanium, Black Titanium",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#b45309",
        "variants": [
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 524999},
            {"variant_label": "8GB RAM / 512GB Storage", "ram_gb": 8, "storage_gb": 512, "price_pkr": 589999},
            {"variant_label": "8GB RAM / 1TB Storage", "ram_gb": 8, "storage_gb": 1024, "price_pkr": 659999},
        ],
    },
    {
        "brand_slug": "apple",
        "model_name": "iPhone 16",
        "slug": "apple-iphone-16",
        "price_pkr": 339999,
        "pta_status": "PTA Approved (Sample)",
        "availability": "Available",
        "release_date": "2024-09-20",
        "ram_gb": 8,
        "ram_display": "8 GB LPDDR5X",
        "storage_gb": 128,
        "storage_display": "128GB / 256GB / 512GB NVMe",
        "processor": "Apple A18 (3 nm) — Hexa-core, Apple 5-core GPU",
        "display_type": "Super Retina XDR OLED, HDR10, Dolby Vision, 2000 nits peak",
        "display_size_inch": 6.1,
        "display_resolution": "1179 x 2556 pixels (~460 ppi)",
        "refresh_rate": "60Hz",
        "main_camera": "48 MP (f/1.6, dual pixel PDAF, sensor-shift OIS) + 12 MP (ultrawide)",
        "selfie_camera": "12 MP (f/1.9, PDAF, SL 3D), 4K@60fps",
        "battery_mah": 3561,
        "charging": "25W wired PD2.0, 25W MagSafe wireless",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "iOS 18",
        "dimensions": "147.6 x 71.6 x 7.8 mm",
        "weight": "170 g",
        "build_material": "Aerospace Aluminum frame, Ceramic Shield front, color-infused glass back",
        "colors": "Ultramarine, Teal, Pink, White, Black",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#4f46e5",
        "variants": [
            {"variant_label": "8GB RAM / 128GB Storage", "ram_gb": 8, "storage_gb": 128, "price_pkr": 339999},
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 379999},
        ],
    },
    {
        "brand_slug": "apple",
        "model_name": "iPhone 15 Pro",
        "slug": "apple-iphone-15-pro",
        "price_pkr": 419999,
        "pta_status": "PTA Approved (Sample)",
        "availability": "Available",
        "release_date": "2023-09-22",
        "ram_gb": 8,
        "ram_display": "8 GB LPDDR5",
        "storage_gb": 256,
        "storage_display": "128GB / 256GB / 512GB NVMe",
        "processor": "Apple A17 Pro (3 nm) — Hexa-core, 6-core GPU",
        "display_type": "LTPO Super Retina XDR OLED, 120Hz, HDR10",
        "display_size_inch": 6.1,
        "display_resolution": "1179 x 2556 pixels (~461 ppi)",
        "refresh_rate": "120Hz",
        "main_camera": "48 MP (wide, OIS) + 12 MP (3x telephoto) + 12 MP (ultrawide) + LiDAR",
        "selfie_camera": "12 MP (wide, OIS), 4K HDR",
        "battery_mah": 3274,
        "charging": "25W wired PD2.0, 15W MagSafe",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "iOS 17 (Upgradable to iOS 18)",
        "dimensions": "146.6 x 70.6 x 8.3 mm",
        "weight": "187 g",
        "build_material": "Titanium frame, Ceramic Shield front",
        "colors": "Blue Titanium, Natural Titanium, White Titanium, Black Titanium",
        "is_latest": 0,
        "is_popular": 1,
        "secondary_hex": "#1e40af",
        "variants": [
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 419999},
        ],
    },

    # SAMSUNG
    {
        "brand_slug": "samsung",
        "model_name": "Galaxy S24 Ultra",
        "slug": "samsung-galaxy-s24-ultra",
        "price_pkr": 434999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-01-24",
        "ram_gb": 12,
        "ram_display": "12 GB LPDDR5X",
        "storage_gb": 256,
        "storage_display": "256GB / 512GB / 1TB UFS 4.0",
        "processor": "Qualcomm Snapdragon 8 Gen 3 for Galaxy (4 nm) — Octa-core up to 3.39 GHz, Adreno 750",
        "display_type": "Dynamic LTPO AMOLED 2X, 120Hz, HDR10+, 2600 nits, Corning Gorilla Armor",
        "display_size_inch": 6.8,
        "display_resolution": "1440 x 3120 pixels (~505 ppi)",
        "refresh_rate": "120Hz LTPO",
        "main_camera": "200 MP (wide, OIS) + 50 MP (periscope 5x optical zoom) + 10 MP (3x telephoto) + 12 MP (ultrawide)",
        "selfie_camera": "12 MP (f/2.2, Dual Pixel PDAF), 4K@60fps",
        "battery_mah": 5000,
        "charging": "45W wired PD3.0, 15W wireless (Qi/PMA), 4.5W reverse wireless",
        "network": "GSM / CDMA / HSPA / EVDO / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, One UI 6.1.1 (7 Years OS Updates)",
        "dimensions": "162.3 x 79 x 8.6 mm",
        "weight": "232 g (Built-in S-Pen)",
        "build_material": "Titanium frame, Gorilla Armor front & back, IP68",
        "colors": "Titanium Gray, Titanium Black, Titanium Violet, Titanium Yellow",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#4338ca",
        "variants": [
            {"variant_label": "12GB RAM / 256GB Storage", "ram_gb": 12, "storage_gb": 256, "price_pkr": 434999},
            {"variant_label": "12GB RAM / 512GB Storage", "ram_gb": 12, "storage_gb": 512, "price_pkr": 469999},
        ],
    },
    {
        "brand_slug": "samsung",
        "model_name": "Galaxy A55 5G",
        "slug": "samsung-galaxy-a55-5g",
        "price_pkr": 134999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-03-15",
        "ram_gb": 8,
        "ram_display": "8 GB / 12 GB LPDDR5",
        "storage_gb": 256,
        "storage_display": "128GB / 256GB + microSDXC",
        "processor": "Exynos 1480 (4 nm) — Octa-core (4x2.75 GHz & 4x2.0 GHz), Xclipse 530 GPU",
        "display_type": "Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM), Gorilla Glass Victus+",
        "display_size_inch": 6.6,
        "display_resolution": "1080 x 2340 pixels (~390 ppi)",
        "refresh_rate": "120Hz",
        "main_camera": "50 MP (f/1.8, PDAF, OIS) + 12 MP (ultrawide) + 5 MP (macro)",
        "selfie_camera": "32 MP (f/2.2, wide), 4K@30fps",
        "battery_mah": 5000,
        "charging": "25W wired fast charging",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, One UI 6.1",
        "dimensions": "161.1 x 77.4 x 8.2 mm",
        "weight": "213 g",
        "build_material": "Brushed Aluminum frame, Gorilla Glass Victus+ front, IP67",
        "colors": "Iceblue, Lilac, Navy, Lemon",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#0284c7",
        "variants": [
            {"variant_label": "8GB RAM / 128GB Storage", "ram_gb": 8, "storage_gb": 128, "price_pkr": 124999},
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 134999},
        ],
    },
    {
        "brand_slug": "samsung",
        "model_name": "Galaxy A15",
        "slug": "samsung-galaxy-a15",
        "price_pkr": 52999,
        "pta_status": "PTA Approved / Local Assembly (Sample)",
        "availability": "Available",
        "release_date": "2023-12-16",
        "ram_gb": 6,
        "ram_display": "6 GB / 8 GB RAM",
        "storage_gb": 128,
        "storage_display": "128GB / 256GB + microSD",
        "processor": "MediaTek Helio G99 (6 nm) — Octa-core (2x2.2 GHz & 6x2.0 GHz), Mali-G57 MC2",
        "display_type": "Super AMOLED, 90Hz, 800 nits (HBM)",
        "display_size_inch": 6.5,
        "display_resolution": "1080 x 2340 pixels (~396 ppi)",
        "refresh_rate": "90Hz",
        "main_camera": "50 MP (wide, AF) + 5 MP (ultrawide) + 2 MP (macro)",
        "selfie_camera": "13 MP (f/2.0, wide), 1080p@30fps",
        "battery_mah": 5000,
        "charging": "25W wired fast charging",
        "network": "GSM / HSPA / 4G LTE",
        "is_5g": 0,
        "os": "Android 14, One UI 6",
        "dimensions": "160.1 x 76.8 x 8.4 mm",
        "weight": "200 g",
        "build_material": "Glass front, polycarbonate frame & back",
        "colors": "Brave Black, Optimistic Blue, Magical Blue, Yellow",
        "is_latest": 0,
        "is_popular": 1,
        "secondary_hex": "#2563eb",
        "variants": [
            {"variant_label": "6GB RAM / 128GB Storage", "ram_gb": 6, "storage_gb": 128, "price_pkr": 52999},
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 59999},
        ],
    },

    # XIAOMI
    {
        "brand_slug": "xiaomi",
        "model_name": "Xiaomi 14 Ultra",
        "slug": "xiaomi-14-ultra",
        "price_pkr": 369999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-02-22",
        "ram_gb": 16,
        "ram_display": "16 GB LPDDR5X",
        "storage_gb": 512,
        "storage_display": "512GB UFS 4.0",
        "processor": "Qualcomm Snapdragon 8 Gen 3 (4 nm) — Octa-core up to 3.3 GHz, Adreno 750",
        "display_type": "LTPO AMOLED, 68B colors, 120Hz, Dolby Vision, HDR10+, 3000 nits peak",
        "display_size_inch": 6.73,
        "display_resolution": "1440 x 3200 pixels (~522 ppi)",
        "refresh_rate": "120Hz LTPO",
        "main_camera": "Quad 50 MP Leica Summilux Lenses (1-inch main variable aperture + 3.2x + 5x periscope + ultrawide)",
        "selfie_camera": "32 MP (f/2.0, wide), 4K@60fps",
        "battery_mah": 5000,
        "charging": "90W wired HyperCharge, 80W wireless charging, 10W reverse wireless",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, Xiaomi HyperOS",
        "dimensions": "161.4 x 75.3 x 9.2 mm",
        "weight": "219.8 g",
        "build_material": "Shield Glass, Aluminum frame, Nano-tech vegan leather back, IP68",
        "colors": "Black, White, Titanium Special Edition",
        "is_latest": 1,
        "is_popular": 0,
        "secondary_hex": "#ea580c",
        "variants": [
            {"variant_label": "16GB RAM / 512GB Storage", "ram_gb": 16, "storage_gb": 512, "price_pkr": 369999},
        ],
    },
    {
        "brand_slug": "xiaomi",
        "model_name": "Redmi Note 13 Pro+ 5G",
        "slug": "xiaomi-redmi-note-13-pro-plus-5g",
        "price_pkr": 129999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-01-15",
        "ram_gb": 12,
        "ram_display": "12 GB LPDDR5",
        "storage_gb": 512,
        "storage_display": "512GB UFS 3.1",
        "processor": "MediaTek Dimensity 7200-Ultra (4 nm) — Octa-core up to 2.8 GHz, Mali-G610 MC4",
        "display_type": "Curved AMOLED, 68B colors, 120Hz, Dolby Vision, HDR10+, 1800 nits, Gorilla Glass Victus",
        "display_size_inch": 6.67,
        "display_resolution": "1220 x 2712 pixels (~446 ppi)",
        "refresh_rate": "120Hz",
        "main_camera": "200 MP (f/1.7, OIS, multi-directional PDAF) + 8 MP (ultrawide) + 2 MP (macro)",
        "selfie_camera": "16 MP (f/2.4, wide), 1080p@60fps",
        "battery_mah": 5000,
        "charging": "120W HyperCharge (100% in 19 min advertised)",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, HyperOS",
        "dimensions": "161.4 x 74.2 x 8.9 mm",
        "weight": "204.5 g",
        "build_material": "Gorilla Glass Victus front, Eco-leather or Glass back, IP68 dust/water resistant",
        "colors": "Midnight Black, Moonlight White, Aurora Purple",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#c2410c",
        "variants": [
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 114999},
            {"variant_label": "12GB RAM / 512GB Storage", "ram_gb": 12, "storage_gb": 512, "price_pkr": 129999},
        ],
    },
    {
        "brand_slug": "xiaomi",
        "model_name": "Redmi Note 13",
        "slug": "xiaomi-redmi-note-13",
        "price_pkr": 54999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-01-15",
        "ram_gb": 8,
        "ram_display": "8 GB LPDDR4X",
        "storage_gb": 256,
        "storage_display": "128GB / 256GB UFS 2.2",
        "processor": "Qualcomm Snapdragon 685 (6 nm) — Octa-core up to 2.8 GHz, Adreno 610",
        "display_type": "AMOLED, 120Hz, 1800 nits peak, Gorilla Glass 3",
        "display_size_inch": 6.67,
        "display_resolution": "1080 x 2400 pixels (~395 ppi)",
        "refresh_rate": "120Hz",
        "main_camera": "108 MP (f/1.8, wide) + 8 MP (ultrawide) + 2 MP (depth)",
        "selfie_camera": "16 MP (f/2.4, wide)",
        "battery_mah": 5000,
        "charging": "33W wired fast charging",
        "network": "GSM / HSPA / 4G LTE",
        "is_5g": 0,
        "os": "Android 13 / HyperOS",
        "dimensions": "162.3 x 75.6 x 8.0 mm",
        "weight": "188.5 g",
        "build_material": "Glass front, IP54 splash resistant",
        "colors": "Midnight Black, Mint Green, Ice Blue, Ocean Sunset",
        "is_latest": 0,
        "is_popular": 1,
        "secondary_hex": "#f97316",
        "variants": [
            {"variant_label": "8GB RAM / 128GB Storage", "ram_gb": 8, "storage_gb": 128, "price_pkr": 49999},
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 54999},
        ],
    },

    # VIVO
    {
        "brand_slug": "vivo",
        "model_name": "Vivo V40 5G",
        "slug": "vivo-v40-5g",
        "price_pkr": 139999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-08-07",
        "ram_gb": 12,
        "ram_display": "12 GB LPDDR4X (+12GB Extended)",
        "storage_gb": 256,
        "storage_display": "256GB / 512GB UFS 2.2",
        "processor": "Qualcomm Snapdragon 7 Gen 3 (4 nm) — Octa-core up to 2.63 GHz, Adreno 720",
        "display_type": "AMOLED, 1B colors, 120Hz, HDR10+, 4500 nits local peak",
        "display_size_inch": 6.78,
        "display_resolution": "1260 x 2800 pixels (~453 ppi)",
        "refresh_rate": "120Hz",
        "main_camera": "50 MP ZEISS (f/1.9, OIS) + 50 MP ZEISS (ultrawide, AF), Ring-LED Aura Light",
        "selfie_camera": "50 MP ZEISS Group Selfie (f/2.0, AF), 4K@30fps",
        "battery_mah": 5500,
        "charging": "80W wired FlashCharge",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, Funtouch OS 14",
        "dimensions": "164.2 x 75.0 x 7.58 mm",
        "weight": "190 g",
        "build_material": "Schott Xensation Alpha glass front, glass back, IP68/IP69",
        "colors": "Stellar Silver, Nebula Purple, Ganges Blue",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#0284c7",
        "variants": [
            {"variant_label": "12GB RAM / 256GB Storage", "ram_gb": 12, "storage_gb": 256, "price_pkr": 139999},
            {"variant_label": "12GB RAM / 512GB Storage", "ram_gb": 12, "storage_gb": 512, "price_pkr": 149999},
        ],
    },
    {
        "brand_slug": "vivo",
        "model_name": "Vivo V30e 5G",
        "slug": "vivo-v30e-5g",
        "price_pkr": 89999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-05-02",
        "ram_gb": 8,
        "ram_display": "8 GB RAM",
        "storage_gb": 256,
        "storage_display": "256GB Storage",
        "processor": "Qualcomm Snapdragon 6 Gen 1 (4 nm) — Octa-core, Adreno 710",
        "display_type": "3D Curved AMOLED, 120Hz, 1300 nits",
        "display_size_inch": 6.78,
        "display_resolution": "1080 x 2400 pixels (~388 ppi)",
        "refresh_rate": "120Hz",
        "main_camera": "50 MP Sony IMX882 (OIS) + 8 MP (ultrawide), Aura Light Portrait",
        "selfie_camera": "32 MP (wide), 1080p",
        "battery_mah": 5500,
        "charging": "44W wired FlashCharge",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, Funtouch 14",
        "dimensions": "164.4 x 74.8 x 7.7 mm",
        "weight": "179 g",
        "build_material": "Glass front, IP64 dust/splash resistant",
        "colors": "Velvet Red, Silk Blue, Sky Mirror",
        "is_latest": 1,
        "is_popular": 0,
        "secondary_hex": "#0369a1",
        "variants": [
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 89999},
        ],
    },
    {
        "brand_slug": "vivo",
        "model_name": "Vivo Y100",
        "slug": "vivo-y100",
        "price_pkr": 57999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-04-20",
        "ram_gb": 8,
        "ram_display": "8 GB LPDDR4X",
        "storage_gb": 256,
        "storage_display": "256GB UFS 2.2",
        "processor": "Qualcomm Snapdragon 685 (6 nm) — Octa-core",
        "display_type": "AMOLED, 120Hz, 1800 nits peak",
        "display_size_inch": 6.67,
        "display_resolution": "1080 x 2400 pixels",
        "refresh_rate": "120Hz",
        "main_camera": "50 MP (wide) + 2 MP (bokeh) + Flicker sensor",
        "selfie_camera": "8 MP (wide)",
        "battery_mah": 5000,
        "charging": "80W wired FlashCharge",
        "network": "GSM / HSPA / 4G LTE",
        "is_5g": 0,
        "os": "Android 14, Funtouch 14",
        "dimensions": "163.2 x 75.8 x 7.8 mm",
        "weight": "186 g",
        "build_material": "Color-changing Breeze Green Leather / Crystal Black",
        "colors": "Breeze Green, Crystal Black",
        "is_latest": 0,
        "is_popular": 1,
        "secondary_hex": "#0891b2",
        "variants": [
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 57999},
        ],
    },

    # OPPO
    {
        "brand_slug": "oppo",
        "model_name": "Oppo Reno 12 5G",
        "slug": "oppo-reno-12-5g",
        "price_pkr": 119999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-06-25",
        "ram_gb": 12,
        "ram_display": "12 GB LPDDR4X",
        "storage_gb": 256,
        "storage_display": "256GB / 512GB UFS 3.1",
        "processor": "MediaTek Dimensity 7300-Energy (4 nm) — Octa-core, Mali-G615 MC2",
        "display_type": "3D Flexible AMOLED, 1B colors, 120Hz, HDR10+, Gorilla Glass 7i",
        "display_size_inch": 6.7,
        "display_resolution": "1080 x 2412 pixels (~394 ppi)",
        "refresh_rate": "120Hz",
        "main_camera": "50 MP Sony LYT-600 (OIS) + 8 MP (ultrawide) + 2 MP (macro)",
        "selfie_camera": "32 MP (f/2.0, AF), 4K@30fps",
        "battery_mah": 5000,
        "charging": "80W SuperVOOC (100% in 46 min)",
        "network": "GSM / HSPA / LTE / 5G + BeaconLink",
        "is_5g": 1,
        "os": "Android 14, ColorOS 14.1 with Oppo AI",
        "dimensions": "161.4 x 74.1 x 7.6 mm",
        "weight": "177 g",
        "build_material": "All-Round Armour body, Gorilla Glass 7i, IP65",
        "colors": "Astro Silver, Matte Brown, Sunset Pink",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#059669",
        "variants": [
            {"variant_label": "12GB RAM / 256GB Storage", "ram_gb": 12, "storage_gb": 256, "price_pkr": 119999},
            {"variant_label": "12GB RAM / 512GB Storage", "ram_gb": 12, "storage_gb": 512, "price_pkr": 134999},
        ],
    },
    {
        "brand_slug": "oppo",
        "model_name": "Oppo Reno 11F 5G",
        "slug": "oppo-reno-11f-5g",
        "price_pkr": 79999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-03-10",
        "ram_gb": 8,
        "ram_display": "8 GB RAM",
        "storage_gb": 256,
        "storage_display": "256GB UFS 3.1",
        "processor": "MediaTek Dimensity 7050 (6 nm) — Octa-core up to 2.6 GHz",
        "display_type": "AMOLED, 1B colors, 120Hz, HDR10+, Panda Glass",
        "display_size_inch": 6.7,
        "display_resolution": "1080 x 2412 pixels",
        "refresh_rate": "120Hz",
        "main_camera": "64 MP (wide, PDAF) + 8 MP (ultrawide) + 2 MP (macro)",
        "selfie_camera": "32 MP (wide), 4K@30fps",
        "battery_mah": 5000,
        "charging": "67W SuperVOOC",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, ColorOS 14",
        "dimensions": "161.1 x 74.7 x 7.5 mm",
        "weight": "177 g",
        "build_material": "Panda Glass front, IP65 dust/water resistant",
        "colors": "Palm Green, Ocean Blue, Coral Purple",
        "is_latest": 0,
        "is_popular": 1,
        "secondary_hex": "#10b981",
        "variants": [
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 79999},
        ],
    },
    {
        "brand_slug": "oppo",
        "model_name": "Oppo A60",
        "slug": "oppo-a60",
        "price_pkr": 54999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-05-12",
        "ram_gb": 8,
        "ram_display": "8 GB LPDDR4X",
        "storage_gb": 256,
        "storage_display": "128GB / 256GB UFS 2.2",
        "processor": "Qualcomm Snapdragon 680 4G (6 nm) — Octa-core",
        "display_type": "IPS LCD, 90Hz, 950 nits (HBM), Splash Touch",
        "display_size_inch": 6.67,
        "display_resolution": "720 x 1604 pixels",
        "refresh_rate": "90Hz",
        "main_camera": "50 MP (wide, PDAF) + 2 MP (depth)",
        "selfie_camera": "8 MP (wide)",
        "battery_mah": 5000,
        "charging": "45W SuperVOOC",
        "network": "GSM / HSPA / 4G LTE",
        "is_5g": 0,
        "os": "Android 14, ColorOS 14",
        "dimensions": "165.7 x 76.0 x 7.7 mm",
        "weight": "186 g",
        "build_material": "MIL-STD-810H shock resistance, IP54",
        "colors": "Ripple Blue, Midnight Purple",
        "is_latest": 0,
        "is_popular": 0,
        "secondary_hex": "#047857",
        "variants": [
            {"variant_label": "8GB RAM / 128GB Storage", "ram_gb": 8, "storage_gb": 128, "price_pkr": 49999},
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 54999},
        ],
    },

    # ONEPLUS
    {
        "brand_slug": "oneplus",
        "model_name": "OnePlus 12 5G",
        "slug": "oneplus-12-5g",
        "price_pkr": 279999,
        "pta_status": "PTA Approved (Sample)",
        "availability": "Available",
        "release_date": "2024-01-23",
        "ram_gb": 16,
        "ram_display": "12 GB / 16 GB LPDDR5X",
        "storage_gb": 512,
        "storage_display": "256GB / 512GB UFS 4.0",
        "processor": "Qualcomm Snapdragon 8 Gen 3 (4 nm) — Octa-core, Adreno 750",
        "display_type": "LTPO AMOLED, 1B colors, 120Hz, Dolby Vision, 4500 nits peak, Gorilla Glass Victus 2",
        "display_size_inch": 6.82,
        "display_resolution": "1440 x 3168 pixels (~510 ppi)",
        "refresh_rate": "120Hz LTPO",
        "main_camera": "50 MP Sony LYT-808 (OIS) + 64 MP (3x periscope telephoto, OIS) + 48 MP (ultrawide), Hasselblad Color",
        "selfie_camera": "32 MP (f/2.4, wide), 4K@30fps",
        "battery_mah": 5400,
        "charging": "100W wired SuperVOOC, 50W AIRVOOC wireless",
        "network": "GSM / CDMA / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, OxygenOS 14",
        "dimensions": "164.3 x 75.8 x 9.2 mm",
        "weight": "220 g",
        "build_material": "Gorilla Glass Victus 2 front, Aluminum frame, IP65",
        "colors": "Flowy Emerald, Silky Black, Glacial White",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#dc2626",
        "variants": [
            {"variant_label": "12GB RAM / 256GB Storage", "ram_gb": 12, "storage_gb": 256, "price_pkr": 254999},
            {"variant_label": "16GB RAM / 512GB Storage", "ram_gb": 16, "storage_gb": 512, "price_pkr": 279999},
        ],
    },
    {
        "brand_slug": "oneplus",
        "model_name": "OnePlus Nord 4 5G",
        "slug": "oneplus-nord-4-5g",
        "price_pkr": 154999,
        "pta_status": "PTA Approved (Sample)",
        "availability": "Available",
        "release_date": "2024-07-16",
        "ram_gb": 12,
        "ram_display": "12 GB LPDDR5X",
        "storage_gb": 256,
        "storage_display": "256GB / 512GB UFS 4.0",
        "processor": "Qualcomm Snapdragon 7+ Gen 3 (4 nm) — Octa-core up to 2.8 GHz, Adreno 732",
        "display_type": "Fluid AMOLED, 1B colors, 120Hz, HDR10+, 2150 nits peak",
        "display_size_inch": 6.74,
        "display_resolution": "1240 x 2772 pixels (~450 ppi)",
        "refresh_rate": "120Hz",
        "main_camera": "50 MP Sony LYTIA (f/1.8, OIS) + 8 MP (ultrawide)",
        "selfie_camera": "16 MP (f/2.4, wide)",
        "battery_mah": 5500,
        "charging": "100W wired SuperVOOC (100% in 28 min)",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, OxygenOS 14.1",
        "dimensions": "162.6 x 75.0 x 8.0 mm",
        "weight": "199.5 g",
        "build_material": "Metal Unibody Aluminum chassis, IP65",
        "colors": "Mercurial Silver, Oasis Green, Obsidian Midnight",
        "is_latest": 1,
        "is_popular": 0,
        "secondary_hex": "#b91c1c",
        "variants": [
            {"variant_label": "12GB RAM / 256GB Storage", "ram_gb": 12, "storage_gb": 256, "price_pkr": 154999},
        ],
    },
    {
        "brand_slug": "oneplus",
        "model_name": "OnePlus Nord CE 4 Lite 5G",
        "slug": "oneplus-nord-ce-4-lite-5g",
        "price_pkr": 84999,
        "pta_status": "PTA Approved (Sample)",
        "availability": "Available",
        "release_date": "2024-06-24",
        "ram_gb": 8,
        "ram_display": "8 GB LPDDR4X",
        "storage_gb": 256,
        "storage_display": "256GB UFS 2.2",
        "processor": "Qualcomm Snapdragon 695 5G (6 nm)",
        "display_type": "AMOLED, 120Hz, 2100 nits peak, Aqua Touch",
        "display_size_inch": 6.67,
        "display_resolution": "1080 x 2400 pixels",
        "refresh_rate": "120Hz",
        "main_camera": "50 MP Sony LYT-600 (OIS) + 2 MP (depth)",
        "selfie_camera": "16 MP (wide)",
        "battery_mah": 5500,
        "charging": "80W wired SuperVOOC",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, OxygenOS 14",
        "dimensions": "162.9 x 75.6 x 8.1 mm",
        "weight": "191 g",
        "build_material": "Glass front, polycarbonate frame, IP54",
        "colors": "Super Silver, Mega Blue, Ultra Orange",
        "is_latest": 0,
        "is_popular": 0,
        "secondary_hex": "#ef4444",
        "variants": [
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 84999},
        ],
    },

    # REALME
    {
        "brand_slug": "realme",
        "model_name": "Realme GT 6 5G",
        "slug": "realme-gt-6-5g",
        "price_pkr": 149999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-06-20",
        "ram_gb": 12,
        "ram_display": "12 GB / 16 GB LPDDR5X",
        "storage_gb": 256,
        "storage_display": "256GB / 512GB UFS 4.0",
        "processor": "Qualcomm Snapdragon 8s Gen 3 (4 nm) — Octa-core up to 3.0 GHz, Adreno 735",
        "display_type": "LTPO AMOLED, 1B colors, 120Hz, HDR10+, Dolby Vision, 6000 nits local peak, Gorilla Glass Victus 2",
        "display_size_inch": 6.78,
        "display_resolution": "1264 x 2780 pixels (~450 ppi)",
        "refresh_rate": "120Hz LTPO",
        "main_camera": "50 MP Sony LYT-808 (f/1.7, OIS) + 50 MP (2x telephoto) + 8 MP (ultrawide)",
        "selfie_camera": "32 MP (f/2.5, wide), 4K@30fps",
        "battery_mah": 5500,
        "charging": "120W SuperVOOC (50% in 10 min)",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, Realme UI 5.0",
        "dimensions": "162 x 75.1 x 8.6 mm",
        "weight": "199 g",
        "build_material": "Nano-mirror glass design, Gorilla Glass Victus 2, IP65",
        "colors": "Fluid Silver, Razor Green",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#ca8a04",
        "variants": [
            {"variant_label": "12GB RAM / 256GB Storage", "ram_gb": 12, "storage_gb": 256, "price_pkr": 149999},
            {"variant_label": "16GB RAM / 512GB Storage", "ram_gb": 16, "storage_gb": 512, "price_pkr": 169999},
        ],
    },
    {
        "brand_slug": "realme",
        "model_name": "Realme 12 Pro+ 5G",
        "slug": "realme-12-pro-plus-5g",
        "price_pkr": 109999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-02-15",
        "ram_gb": 12,
        "ram_display": "12 GB RAM",
        "storage_gb": 512,
        "storage_display": "512GB Storage",
        "processor": "Qualcomm Snapdragon 7s Gen 2 (4 nm) — Octa-core, Adreno 710",
        "display_type": "Curved AMOLED, 1B colors, 120Hz, 950 nits",
        "display_size_inch": 6.7,
        "display_resolution": "1080 x 2412 pixels",
        "refresh_rate": "120Hz",
        "main_camera": "50 MP Sony IMX890 (OIS) + 64 MP (3x Periscope Portrait OIS) + 8 MP (ultrawide)",
        "selfie_camera": "32 MP Sony (wide)",
        "battery_mah": 5000,
        "charging": "67W SuperVOOC",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, Realme UI 5.0",
        "dimensions": "161.5 x 74.0 x 8.8 mm",
        "weight": "196 g",
        "build_material": "Luxury Watch Bezel & Vegan Leather back, IP65",
        "colors": "Submarine Blue, Navigator Beige, Explorer Red",
        "is_latest": 0,
        "is_popular": 1,
        "secondary_hex": "#d97706",
        "variants": [
            {"variant_label": "12GB RAM / 512GB Storage", "ram_gb": 12, "storage_gb": 512, "price_pkr": 109999},
        ],
    },
    {
        "brand_slug": "realme",
        "model_name": "Realme C67",
        "slug": "realme-c67",
        "price_pkr": 42999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-01-10",
        "ram_gb": 8,
        "ram_display": "8 GB LPDDR4X",
        "storage_gb": 128,
        "storage_display": "128GB / 256GB",
        "processor": "Qualcomm Snapdragon 685 (6 nm) — Octa-core",
        "display_type": "IPS LCD, 90Hz, 950 nits, Mini Capsule 2.0",
        "display_size_inch": 6.72,
        "display_resolution": "1080 x 2400 pixels",
        "refresh_rate": "90Hz",
        "main_camera": "108 MP (3x In-sensor Zoom) + 2 MP (depth)",
        "selfie_camera": "8 MP (wide)",
        "battery_mah": 5000,
        "charging": "33W SuperVOOC",
        "network": "GSM / HSPA / 4G LTE",
        "is_5g": 0,
        "os": "Android 14, Realme UI",
        "dimensions": "164.6 x 75.4 x 7.6 mm",
        "weight": "185 g",
        "build_material": "Sunny Oasis textured polycarbonate, IP54",
        "colors": "Sunny Oasis, Black Rock",
        "is_latest": 0,
        "is_popular": 1,
        "secondary_hex": "#eab308",
        "variants": [
            {"variant_label": "8GB RAM / 128GB Storage", "ram_gb": 8, "storage_gb": 128, "price_pkr": 42999},
        ],
    },

    # INFINIX
    {
        "brand_slug": "infinix",
        "model_name": "Infinix GT 20 Pro",
        "slug": "infinix-gt-20-pro",
        "price_pkr": 99999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-05-15",
        "ram_gb": 12,
        "ram_display": "12 GB LPDDR5X (+12GB Extended)",
        "storage_gb": 256,
        "storage_display": "256GB UFS 3.1",
        "processor": "MediaTek Dimensity 8200 Ultimate (4 nm) + Pixelworks X5 Turbo Gaming Display Chip",
        "display_type": "Bezel-less AMOLED, 144Hz Esports Refresh Rate, 1300 nits peak",
        "display_size_inch": 6.78,
        "display_resolution": "1080 x 2436 pixels (~393 ppi)",
        "refresh_rate": "144Hz",
        "main_camera": "108 MP Samsung HM6 (OIS) + 2 MP (macro) + 2 MP (depth), 4K@60fps",
        "selfie_camera": "32 MP (wide), 1440p@30fps",
        "battery_mah": 5000,
        "charging": "45W PD3.0 + Bypass Charging Mode + Hyper Charge",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, Clean XOS 14 for GT (No Bloatware)",
        "dimensions": "164.3 x 75.4 x 8.2 mm",
        "weight": "194 g",
        "build_material": "Cyber Mecha Loop RGB LED Back Panel, JBL Dual Speakers, IP54",
        "colors": "Mecha Blue, Mecha Orange, Mecha Silver",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#7c3aed",
        "variants": [
            {"variant_label": "12GB RAM / 256GB Storage", "ram_gb": 12, "storage_gb": 256, "price_pkr": 99999},
        ],
    },
    {
        "brand_slug": "infinix",
        "model_name": "Infinix Note 40 Pro",
        "slug": "infinix-note-40-pro",
        "price_pkr": 69999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-03-28",
        "ram_gb": 12,
        "ram_display": "12 GB LPDDR4X",
        "storage_gb": 256,
        "storage_display": "256GB UFS 2.2",
        "processor": "MediaTek Helio G99 Ultimate (6 nm) + Cheetah X1 Power Management Chip",
        "display_type": "55-Degree 3D Curved AMOLED, 120Hz, 1300 nits, Gorilla Glass",
        "display_size_inch": 6.78,
        "display_resolution": "1080 x 2436 pixels",
        "refresh_rate": "120Hz",
        "main_camera": "108 MP (f/1.8, OIS, 3x Lossless Superzoom) + 2 MP + 2 MP",
        "selfie_camera": "32 MP (f/2.2, wide, Dual LED flash)",
        "battery_mah": 5000,
        "charging": "70W All-Round FastCharge 2.0 + 20W Wireless MagCharge included",
        "network": "GSM / HSPA / 4G LTE",
        "is_5g": 0,
        "os": "Android 14, XOS 14",
        "dimensions": "164.4 x 74.6 x 7.8 mm",
        "weight": "190 g",
        "build_material": "Curved Gorilla Glass front, Vintage Green Vegan Leather, Active Halo AI Lighting",
        "colors": "Vintage Green, Titan Gold, Obsidian Black",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#6d28d9",
        "variants": [
            {"variant_label": "12GB RAM / 256GB Storage", "ram_gb": 12, "storage_gb": 256, "price_pkr": 69999},
        ],
    },
    {
        "brand_slug": "infinix",
        "model_name": "Infinix Hot 40 Pro",
        "slug": "infinix-hot-40-pro",
        "price_pkr": 42999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-01-05",
        "ram_gb": 8,
        "ram_display": "8 GB RAM (+8GB Extended)",
        "storage_gb": 256,
        "storage_display": "256GB UFS 2.2",
        "processor": "MediaTek Helio G99 (6 nm) with Metamaterial Gaming Antenna",
        "display_type": "IPS LCD, 120Hz, Magic Ring UI",
        "display_size_inch": 6.78,
        "display_resolution": "1080 x 2460 pixels",
        "refresh_rate": "120Hz",
        "main_camera": "108 MP (f/1.8, HM6 sensor) + 2 MP (macro) + AI lens",
        "selfie_camera": "32 MP (wide, Dual flash)",
        "battery_mah": 5000,
        "charging": "33W Enduring FastCharge",
        "network": "GSM / HSPA / 4G LTE",
        "is_5g": 0,
        "os": "Android 13, XOS 13.5",
        "dimensions": "168.6 x 76.6 x 8.3 mm",
        "weight": "199 g",
        "build_material": "Starfall crystal finish",
        "colors": "Palm Blue, Horizon Gold, Starlit Black, Starfall Green",
        "is_latest": 0,
        "is_popular": 1,
        "secondary_hex": "#8b5cf6",
        "variants": [
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 42999},
        ],
    },

    # TECNO
    {
        "brand_slug": "tecno",
        "model_name": "Tecno Camon 30 Pro 5G",
        "slug": "tecno-camon-30-pro-5g",
        "price_pkr": 99999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-04-18",
        "ram_gb": 12,
        "ram_display": "12 GB LPDDR5X",
        "storage_gb": 512,
        "storage_display": "512GB UFS 3.1",
        "processor": "MediaTek Dimensity 8200 Ultimate (4 nm) — Octa-core up to 3.1 GHz",
        "display_type": "AMOLED, 144Hz Refresh Rate, HDR10+",
        "display_size_inch": 6.78,
        "display_resolution": "1080 x 2436 pixels (~393 ppi)",
        "refresh_rate": "144Hz",
        "main_camera": "50 MP Sony IMX890 (1/1.56\", OIS) + 50 MP (ultrawide, AF) + 2 MP (depth), 4K@60fps HDR",
        "selfie_camera": "50 MP (Eye-tracking AutoFocus), 4K@30fps",
        "battery_mah": 5000,
        "charging": "70W Ultra Charge (100% in 47 min)",
        "network": "GSM / HSPA / LTE / 5G",
        "is_5g": 1,
        "os": "Android 14, HiOS 14",
        "dimensions": "164 x 74.5 x 7.7 mm",
        "weight": "188 g",
        "build_material": "Classic Rangefinder Camera aesthetic, Tech-Art Suede Leather, Dolby Atmos Stereo",
        "colors": "Iceland Basaltic Dark, Alps Snowy Silver",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#0891b2",
        "variants": [
            {"variant_label": "12GB RAM / 512GB Storage", "ram_gb": 12, "storage_gb": 512, "price_pkr": 99999},
        ],
    },
    {
        "brand_slug": "tecno",
        "model_name": "Tecno Camon 30",
        "slug": "tecno-camon-30",
        "price_pkr": 57999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-04-18",
        "ram_gb": 8,
        "ram_display": "8 GB / 12 GB RAM",
        "storage_gb": 256,
        "storage_display": "256GB Storage",
        "processor": "MediaTek Helio G99 Ultimate (6 nm) — Octa-core",
        "display_type": "AMOLED, 120Hz",
        "display_size_inch": 6.78,
        "display_resolution": "1080 x 2436 pixels",
        "refresh_rate": "120Hz",
        "main_camera": "50 MP (f/1.9, OIS, 1/1.57\" sensor) + 2 MP (depth)",
        "selfie_camera": "50 MP (Eye-tracking AF, Dual-color temperature flash)",
        "battery_mah": 5000,
        "charging": "70W Ultra Charge",
        "network": "GSM / HSPA / 4G LTE",
        "is_5g": 0,
        "os": "Android 14, HiOS 14",
        "dimensions": "165.3 x 75.3 x 7.7 mm",
        "weight": "187 g",
        "build_material": "Glass or Eco-Suede back, Action Dot Indicator",
        "colors": "Uyuni Salt White, Iceland Basaltic Dark, Sahara Sand Brown",
        "is_latest": 1,
        "is_popular": 1,
        "secondary_hex": "#06b6d4",
        "variants": [
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 57999},
            {"variant_label": "12GB RAM / 256GB Storage", "ram_gb": 12, "storage_gb": 256, "price_pkr": 62999},
        ],
    },
    {
        "brand_slug": "tecno",
        "model_name": "Tecno Spark 20 Pro+",
        "slug": "tecno-spark-20-pro-plus",
        "price_pkr": 49999,
        "pta_status": "PTA Approved / Official Warranty (Sample)",
        "availability": "Available",
        "release_date": "2024-02-01",
        "ram_gb": 8,
        "ram_display": "8 GB RAM (+8GB Extended)",
        "storage_gb": 256,
        "storage_display": "256GB Storage",
        "processor": "MediaTek Helio G99 Ultimate (6 nm)",
        "display_type": "56.5-Degree Curved AMOLED, 120Hz, 1000 nits",
        "display_size_inch": 6.78,
        "display_resolution": "1080 x 2436 pixels",
        "refresh_rate": "120Hz",
        "main_camera": "108 MP (f/1.75, 3x In-sensor zoom) + 2 MP",
        "selfie_camera": "32 MP (wide, Dual LED flash)",
        "battery_mah": 5000,
        "charging": "33W Super Charge",
        "network": "GSM / HSPA / 4G LTE",
        "is_5g": 0,
        "os": "Android 14, HiOS 14",
        "dimensions": "164.7 x 75.0 x 7.55 mm",
        "weight": "179 g",
        "build_material": "Magic Skin 2.0 Green Leather / Temporal Orbits",
        "colors": "Temporal Orbits, Lunar Frost, Radiant Starstream, Magic Skin Green",
        "is_latest": 0,
        "is_popular": 1,
        "secondary_hex": "#0e7490",
        "variants": [
            {"variant_label": "8GB RAM / 256GB Storage", "ram_gb": 8, "storage_gb": 256, "price_pkr": 49999},
        ],
    },
]


def seed_database_if_empty() -> None:
    init_db()
    conn = get_db_connection()
    cursor = conn.cursor()

    existing_brands = cursor.execute("SELECT COUNT(*) FROM brands").fetchone()[0]
    existing_phones = cursor.execute("SELECT COUNT(*) FROM phones").fetchone()[0]
    if existing_brands > 0 or existing_phones > 0:
        # Database already exists: DO NOT reset, reseed, or overwrite any existing rows!
        # Only ensure that local SVG files exist on disk for existing phones if container restarted.
        rows = cursor.execute(
            "SELECT p.slug, p.model_name, p.image_url, p.is_demo_data, b.name as brand_name, b.accent_color "
            "FROM phones p JOIN brands b ON b.id = p.brand_id"
        ).fetchall()
        conn.close()
        for r in rows:
            if r["image_url"] and r["image_url"].startswith("/static/images/phones/"):
                fname = os.path.basename(r["image_url"])
                disk_path = os.path.join(IMAGES_DIR, fname)
                if not os.path.exists(disk_path) and fname.endswith(".svg"):
                    generate_phone_svg(
                        slug=r["slug"],
                        brand_name=r["brand_name"],
                        model_name=r["model_name"],
                        accent_hex=r["accent_color"],
                        secondary_hex="#1e293b",
                        is_demo=bool(r["is_demo_data"]),
                    )
        return

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    brand_map = {}

    for b in BRANDS_SEED:
        cursor.execute(
            """
            INSERT INTO brands (name, slug, country, tagline, description, accent_color, display_order, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                b["name"],
                b["slug"],
                b["country"],
                b["tagline"],
                b["description"],
                b["accent_color"],
                b["display_order"],
                now_str,
            ),
        )
        brand_map[b["slug"]] = {
            "id": cursor.lastrowid,
            "name": b["name"],
            "accent_color": b["accent_color"],
        }

    for idx, p in enumerate(PHONES_SEED):
        b_info = brand_map[p["brand_slug"]]
        img_url = generate_phone_svg(
            slug=p["slug"],
            brand_name=b_info["name"],
            model_name=p["model_name"],
            accent_hex=b_info["accent_color"],
            secondary_hex=p.get("secondary_hex", "#1e293b"),
            is_demo=True,
        )

        summary = (
            f"{b_info['name']} {p['model_name']} features a {p['display_size_inch']}-inch {p['display_type']} display, "
            f"powered by {p['processor']}, paired with {p['ram_display']} RAM and {p['storage_display']} storage. "
            f"Note: Pre-populated prices (PKR) and specifications are marked as DEMO / SAMPLE DATA and can be edited or verified anytime in the Admin Panel."
        )

        cursor.execute(
            """
            INSERT INTO phones (
                brand_id, model_name, slug, price_pkr, pta_status, availability,
                is_demo_data, data_source_note, image_url, gallery_json, release_date,
                ram_gb, ram_display, storage_gb, storage_display, processor,
                display_type, display_size_inch, display_resolution, refresh_rate,
                main_camera, selfie_camera, battery_mah, charging, network, is_5g,
                os, dimensions, weight, build_material, sim_type, colors, sensors,
                summary_text, is_latest, is_popular, views_count, created_at, updated_at
            ) VALUES (
                ?, ?, ?, ?, ?, ?,
                1, 'DEMO / SAMPLE DATA — Verify official PKR price & specifications via Admin Panel', ?, ?, ?,
                ?, ?, ?, ?, ?,
                ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, 'Dual SIM (Nano-SIM, dual stand-by)', ?, 'Fingerprint (under display/side), Accelerometer, Gyro, Proximity, Compass',
                ?, ?, ?, ?, ?, ?
            )
            """,
            (
                b_info["id"],
                p["model_name"],
                p["slug"],
                p["price_pkr"],
                p["pta_status"],
                p["availability"],
                img_url,
                json.dumps([img_url]),
                p["release_date"],
                p["ram_gb"],
                p["ram_display"],
                p["storage_gb"],
                p["storage_display"],
                p["processor"],
                p["display_type"],
                p["display_size_inch"],
                p["display_resolution"],
                p["refresh_rate"],
                p["main_camera"],
                p["selfie_camera"],
                p["battery_mah"],
                p["charging"],
                p["network"],
                p["is_5g"],
                p["os"],
                p["dimensions"],
                p["weight"],
                p["build_material"],
                p["colors"],
                summary,
                p["is_latest"],
                p["is_popular"],
                120 + (27 - idx) * 18,
                now_str,
                now_str,
            ),
        )
        phone_id = cursor.lastrowid

        for v in p.get("variants", []):
            cursor.execute(
                """
                INSERT INTO phone_variants (phone_id, variant_label, ram_gb, storage_gb, price_pkr)
                VALUES (?, ?, ?, ?, ?)
                """,
                (phone_id, v["variant_label"], v["ram_gb"], v["storage_gb"], v["price_pkr"]),
            )

        cursor.execute(
            """
            INSERT INTO price_history (phone_id, old_price_pkr, new_price_pkr, note, changed_at)
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                phone_id,
                p["price_pkr"],
                p["price_pkr"],
                "Initial Demo / Sample Seed Entry",
                now_str,
            ),
        )

    conn.commit()
    conn.close()


if __name__ == "__main__":
    seed_database_if_empty()
    print("Database initialized and seeded with DEMO / SAMPLE DATA.")
